import math
print("sqrt",math.sqrt(25))
print("pi",math.pi)
print("e",math.e)
print("sin",math.sin(0))
print("cos",math.cos(0))
print("tan",math.tan(0))
print("log",math.log(10))
print("log10",math.log10(10))
print("exp",math.exp(2))
print("pow",math.pow(2,3))
print("ceil",math.ceil(2.3))
print("floor",math.floor(2.3))
print("fabs",math.fabs(-2.3))
print("factorial",math.factorial(5))
print("fmod",math.fmod(10,3))
print("frexp",math.frexp(10))
print("fsum",math.fsum([1,2,3,4,5]))
